### ISSUE TITLE
Overpass http response kód kezelés

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#106]
Internal error when serving /osm/street-housenumbers/lagymanyos/update-result
Traceback (most recent call last):
  File "/home/vmiklos/git/osm-gimmisn/wsgi.py", line 673, in application
    return our_application(environ, start_response)
  File "/home/vmiklos/git/osm-gimmisn/wsgi.py", line 631, in our_application
    output = handle_street_housenumbers(request_uri, workdir, relations)
  File "/home/vmiklos/git/osm-gimmisn/wsgi.py", line 104, in handle_street_housenumbers
    helpers.write_street_housenumbers(workdir, relation, overpass_query.overpass_query(query))
  File "/home/vmiklos/git/osm-gimmisn/overpass_query.py", line 19, in overpass_query
    sock = urlopen(url, bytes(query, "utf-8"))
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
**urllib.error.HTTPError: HTTP Error 504: Gateway Timeout**

**Comment by vasony** [comment]
el kéne kapni az exception-t

**Comment by vmiklos** [comment]
Most ilyet ír, hogy:

````
Overpass hiba: HTTP Error 504: Gateway Timeout
````

Ehelyett, hogy

````
Frissítés sikeres.
````

Ha elszállna a dolog HTTP szinten.
