### ISSUE TITLE
invalid-relations ha még nincs legenerálva egy terület, akkor hibára fut

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1126]
Ha akarjuk kezelni. Újonnan hozzáadott területnél, ha még nincs referencia, akkor az alábbi errort dobja:
(szerintem egyszerűen ki kellene hagynia azt amit nem talál)

```
Belső hiba a /osm/housenumber-stats/hungary/invalid-relations kiszolgálása során
Traceback (most recent call last):
  File "/home/osm-gimmisn/git/osm-gimmisn/wsgi.py", line 943, in application
    return our_application(environ, start_response)
  File "/home/osm-gimmisn/git/osm-gimmisn/wsgi.py", line 928, in our_application
    doc.asis(handler(relations, request_uri).getvalue())
  File "/home/osm-gimmisn/git/osm-gimmisn/webframe.py", line 380, in handle_stats
    return handle_invalid_refstreets(relations)
  File "/home/osm-gimmisn/git/osm-gimmisn/webframe.py", line 358, in handle_invalid_refstreets
    invalid_refstreets = areas.get_invalid_refstreets(relation)
  File "/home/osm-gimmisn/git/osm-gimmisn/areas.py", line 681, in get_invalid_refstreets
    osm_streets = [i.get_osm_name() for i in relation.get_osm_streets()]
  File "/home/osm-gimmisn/git/osm-gimmisn/areas.py", line 354, in get_osm_streets
    with self.get_files().get_osm_streets_csv_stream() as sock:
  File "/home/osm-gimmisn/git/osm-gimmisn/areas.py", line 53, in get_osm_streets_csv_stream
    return util.CsvIO(self.__get_osm_streets_stream("r"))
  File "/home/osm-gimmisn/git/osm-gimmisn/areas.py", line 49, in __get_osm_streets_stream
    return cast(TextIO, open(path, mode=mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/osm-gimmisn/git/osm-gimmisn/workdir/streets-istvantelek.csv'
```

**Comment by vmiklos** [comment]
Jobb kezelni, csúnyák ezek az excepionok.

**Comment by vmiklos** [comment]
lehet tesztelni

**Comment by vasony** [comment]
következő területnél megnézem, szerintem csak napok kérdése az újabb igén csak ezért most nem veszek fel újat.

**Comment by vasony** [comment]
Sarud-ra megy.
