### ISSUE TITLE
ha még nincs yaml adott területhez, a cache exception-t dob

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1225]
Belső hiba a /osm/missing-housenumbers/martonvasar/view-result kiszolgálása során
Traceback (most recent call last):
  File "/home/osm-gimmisn/git/osm-gimmisn/wsgi.py", line 946, in application
    return our_application(environ, start_response)
  File "/home/osm-gimmisn/git/osm-gimmisn/wsgi.py", line 929, in our_application
    doc.asis(handler(relations, request_uri).getvalue())
  File "/home/osm-gimmisn/git/osm-gimmisn/wsgi.py", line 353, in handle_missing_housenumbers
    doc.asis(missing_housenumbers_view_res(relations, request_uri).getvalue())
  File "/home/osm-gimmisn/git/osm-gimmisn/wsgi.py", line 159, in missing_housenumbers_view_res
    doc = cache.get_missing_housenumbers_html(relation)
  File "/home/osm-gimmisn/git/osm-gimmisn/cache.py", line 54, in get_missing_housenumbers_html
    if is_missing_housenumbers_html_cached(relation):
  File "/home/osm-gimmisn/git/osm-gimmisn/cache.py", line 44, in is_missing_housenumbers_html_cached
    relation_mtime = os.path.getmtime(relation_path)
  File "/usr/lib64/python3.9/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/osm-gimmisn/git/osm-gimmisn/data/relation-martonvasar.yaml'

**Comment by vmiklos** [comment]
https://osm-gimmisn.vmiklos.hu/osm/missing-housenumbers/martonvasar/view-result

jogos, holnap megnezem

**Comment by vasony** [comment]
```
if not os.path.exists(relation_path):
        return False
```
ha jól értelmezem, akkor ez kell

**Comment by vmiklos** [comment]
igen, csak igy nem cache-eljuk, ami butasag

**Comment by vmiklos** [comment]
Lehet tesztelni

**Comment by vasony** [comment]
ok
