### ISSUE TITLE
Százalékok nem frissülnek a főoldalon

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#127]
A százalék és utolsó módosítás nem frissül az éjszakai frissítés után. Gondolom a cronban nem fut le a hiányzó házszámos frissítési kör a legvégén.
Ez már egyszer ment, de most megint régi értéket mutat, pl barossgabortelep 39.59, rákattintottam aztán 40.10 lett. 
A dátumok a %-kok mellett is teljesen randomok, gondolom a valóság, amikor meghívódott utoljára.

**Comment by vmiklos** [comment]
Frissülne az, csak elszállt a frissítés:

````
2019-08-14 01:43:48 ERROR main: unhandled exception: Traceback (most recent call last):
  File "/home/vmiklos/git/osm-gimmisn/cron.py", line 140, in main
    our_main(relations)
  File "/home/vmiklos/git/osm-gimmisn/cron.py", line 116, in our_main
    update_street_housenumbers(relations)
  File "/home/vmiklos/git/osm-gimmisn/cron.py", line 77, in update_street_housenumbers
    overpass_sleep()
  File "/home/vmiklos/git/osm-gimmisn/cron.py", line 35, in overpass_sleep
    sleep = overpass_query.overpass_query_need_sleep()
  File "/home/vmiklos/git/osm-gimmisn/overpass_query.py", line 37, in overpass_query_need_sleep
    sleep = int(re.sub(r".*in (\d+) seconds.*", r"\1", line.strip())) + 1
ValueError: invalid literal for int() with base 10: 'Slot available after: 2019-08-14T01:43:47Z, in -1 seconds.'
````

Erre a -1re nem voltam felkészülve. :-) Majd megcsinálom, hogy vegye a negatív számokat 0-nak.

**Comment by vmiklos** [comment]
Remélhetőleg ennyi elég, de azért majd holnap megnézem, hogy szépen lefutott-e újra a cron.
