### ISSUE TITLE
stat: városonkénti elszáll

### ISSUE THREAD

**Issue by vasony** [vmiklos/osm-gimmisn#1508]
A városonkénti most elszáll, valamit **megmockoltál** a dátummal :)
https://osm-gimmisn.vmiklos.hu/osm/housenumber-stats/hungary/cityprogress
```
Belső hiba a /osm/housenumber-stats/hungary/cityprogress kiszolgálása során
Traceback (most recent call last):
  File "/home/osm-gimmisn/git/osm-gimmisn/wsgi.py", line 944, in our_application
    doc.asis(handler(ctx, relations, request_uri).getvalue())
  File "/home/osm-gimmisn/git/osm-gimmisn/webframe.py", line 442, in handle_stats
    return handle_stats_cityprogress(ctx, relations)
  File "/home/osm-gimmisn/git/osm-gimmisn/webframe.py", line 377, in handle_stats_cityprogress
    with open(ctx.get_ini().get_workdir() + "/stats/" + today + ".citycount", "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/osm-gimmisn/git/osm-gimmisn/workdir/stats/2021-07-21.citycount'
```

**Comment by vmiklos** [comment]
Egy helyi idő vs UTC dolgot szúrtam el, abból le a "ma" 22h után "holnap".

**Comment by vmiklos** [comment]
Most már jó kell legyen.
